import Head from 'next/head';
import Link from 'next/link';

import Avatar from '@mui/material/Avatar';
import GitHubIcon from '@mui/icons-material/GitHub';

import styles from './layout.module.scss';

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/avatar.png' />
        <title>Dash</title>
      </Head>

      <header className={styles.header}>
        <Link href='/'>
          <div> </div>
        </Link>
        <Link href='/'>
          <div> </div>
        </Link>
      </header>

      <main className={styles.main}>{children}</main>

      <footer className={styles.footer}>
        <span> Created by Yunhao&nbsp;</span>
        <a href='https://github.com/heyunnnnhao' target='_blank' rel='noopener noreferrer'>
          <GitHubIcon fontSize='small' className={styles.logo} />
        </a>
      </footer>
    </>
  );
}
