import { useState, useEffect } from 'react';

import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';

import GitHubIcon from '@mui/icons-material/GitHub';

import styles from './layout.module.scss';

export default function Layout({ children }) {
  const router = useRouter();
  const location = router.pathname === '/' ? 'home' : '';
  return (
    <>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/avatar.png' />
        <title>Dash</title>
      </Head>

      {location !== 'home' && (
        <header className={styles.header}>
          <Link href='/'>
            <div> back to home</div>
          </Link>
        </header>
      )}

      <main className={styles.main}>{children}</main>

      {location === 'home' && (
        <footer className={styles.footer}>
          <span> Created by Yunhao&nbsp;</span>
          <a href='https://github.com/heyunnnnhao' target='_blank' rel='noopener noreferrer'>
            <GitHubIcon fontSize='small' className={styles.logo} />
          </a>
        </footer>
      )}
    </>
  );
}
